GOOGLE_API_KEY="AIzaSyB0l8s7a43UB6NstI6aERHqTm7LNanP_OE"
NEO4J_URI="neo4j+s://9d19e297.databases.neo4j.io:7687"
NEO4J_USERNAME="neo4j"
NEO4J_PASSWORD="7WQzOIG_aI8oy0LuULNYfO7JChxdzTEFbXHolvWSlMg"
AURA_INSTANCEID="9d19e297"
AURA_INSTANCENAME="Instance01"